version: '3.7'

services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - microservice-network
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - microservice-network
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3308:3308"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    networks:
      - microservice-network
  zipkin:
    image: zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - microservice-network
  configreg:
    image: mahekbaru/configreg:latest
    container_name: config
    ports:
      - "8083:8083"
    depends_on:
      - servicereg
    networks:
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  servicereg:
    image: mahekbaru/servicereg:latest
    container_name: eureka
    ports:
      - "8761:8761"
    depends_on:
      - zookeeper
      - kafka
      - mysql
      - zipkin
    networks:
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  bankapp:
    image: mahekbaru/bankapp:latest
    container_name: customer
    ports:
      - "8081:8081"
    depends_on:
      - servicereg
      - configreg
    networks:
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  loanreg:
    image: mahekbaru/loanreg:latest
    container_name: loan
    ports:
      - "8082:8082"
    depends_on:
      - servicereg
      - configreg
    networks:
      - microservice-network
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  cloudreg:
    image: mahekbaru/cloudreg:latest
    container_name: cloud
    ports:
      - "8080:8080"
    depends_on:
      - servicereg
      - configreg
      - bankapp
      - loanreg
    networks:
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  
networks:
  microservice-network:
    driver: bridge



